skiploom:
  cors:
    allowed-origins: http://localhost:5173

spring:
  config:
    import: optional:configtree:${skiploom.secrets.path:../../secrets}/
  datasource:
    url: jdbc:postgresql://localhost:5432/skiploom-development
    username: postgres
  flyway:
    locations: classpath:db/migration,classpath:db/seed
