skiploom:
  cors:
    allowed-origins: http://localhost:5173

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skiploom-test
    username: postgres
    password: postgres
  flyway:
    locations: classpath:db/migration,classpath:db/seed
