server:
  port: 8080

spring:
  application:
    name: skiploom-backend
  mvc:
    problemdetails:
      enabled: true

logging:
  level:
    root: INFO
    com.skiploom: DEBUG
  file:
    name: logs/skiploom.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
