skiploom:
  cors:
    allowed-origins: http://localhost:5173

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  datasource:
    url: jdbc:postgresql://localhost:5432/skiploom-development
    username: postgres
    password: postgres
  flyway:
    locations: classpath:db/migration,classpath:db/seed
