skiploom:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

spring:
  config:
    import: optional:configtree:/run/secrets/
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
