skiploom:
  cors:
    allowed-origins: http://localhost:5173

spring:
  config:
    import: optional:configtree:src/test/resources/secrets/
  flyway:
    locations: classpath:db/migration,classpath:db/seed
